/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.ResultSet;
import java.sql.Connection;
import database.conexionDB;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import database.CRUD_To_Do;


/**
 *
 * @author User
 */
public class DentroApp extends javax.swing.JFrame{
    Log ID = new Log();
    conexionDB cnx = new conexionDB();
    CRUD_To_Do cursor = new CRUD_To_Do();
    
    public DentroApp() {
        initComponents();
        informacionTareas(ID.ID); 
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        rsscalelabel.RSScaleLabel.setScaleLabel(agg, "/home/darielrdriguez/NetBeansProjects/To-Do/InterfazG/Java interfazG/add-note-4110_J4mvUNczA.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(act, "/home/darielrdriguez/NetBeansProjects/To-Do/InterfazG/Java interfazG/reload-5685_XLZ_AAD5b.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(borr, "/home/darielrdriguez/NetBeansProjects/To-Do/InterfazG/Java interfazG/remove-note-4109_APcswrtQZ.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(comp, "/home/darielrdriguez/NetBeansProjects/To-Do/InterfazG/Java interfazG/happy-emoji-2947_XWI8qzIMz.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agg = new javax.swing.JLabel();
        act = new javax.swing.JLabel();
        borr = new javax.swing.JLabel();
        comp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnagg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnact = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnborr = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btncomp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblista = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtfechainicio = new javax.swing.JTextField();
        txtaggtarea2 = new javax.swing.JTextField();
        txtfechafinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agg.setText("agg");
        jPanel1.add(agg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, 40));

        act.setText("act");
        jPanel1.add(act, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 40, 40));

        borr.setText("borr");
        jPanel1.add(borr, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 40, 40));

        comp.setText("comp");
        jPanel1.add(comp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rectangle 1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 40, 40));

        btnagg.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnagg.setForeground(new java.awt.Color(0, 180, 216));
        btnagg.setText("Agregar");
        btnagg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnagg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnagg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaggActionPerformed(evt);
            }
        });
        jPanel1.add(btnagg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rectangle 1.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 40, 40));

        btnact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnact.setForeground(new java.awt.Color(0, 180, 216));
        btnact.setText("Actualizar");
        btnact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnact.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactActionPerformed(evt);
            }
        });
        jPanel1.add(btnact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rectangle 1.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 40, 40));

        btnborr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnborr.setForeground(new java.awt.Color(0, 180, 216));
        btnborr.setText("Borrar");
        btnborr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnborr.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnborr, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 160, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Rectangle 1.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 50, 50));

        btncomp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncomp.setForeground(new java.awt.Color(0, 180, 216));
        btncomp.setText("Completado");
        btncomp.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btncomp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btncomp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 610, 220, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Group 1124.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tblista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblista);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 650, 450));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Group 112532.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jButton1.setBackground(new java.awt.Color(3, 4, 94));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Volver al menú");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 160, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Group 1130.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 310, -1, -1));

        txtfechainicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfechainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechainicioActionPerformed(evt);
            }
        });
        jPanel1.add(txtfechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 280, 30));

        txtaggtarea2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtaggtarea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaggtarea2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtaggtarea2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 280, 30));

        txtfechafinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtfechafinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechafinalActionPerformed(evt);
            }
        });
        jPanel1.add(txtfechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 280, 30));

        jLabel5.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel5.setText("Agregar Tarea");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 110, 20));

        jLabel7.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Final");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 90, -1));

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel8.setText("Fecha de inicio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 120, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Group 1130.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, -150, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaggActionPerformed
        // TODO add your handling code here:
        cnx.cerrar();
        cursor.agregar(ID.ID, txtaggtarea2.getText(), txtfechainicio.getText(),txtfechafinal.getText());
    }//GEN-LAST:event_btnaggActionPerformed

    private void btnactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnactActionPerformed

    private void txtfechainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechainicioActionPerformed

    private void txtaggtarea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaggtarea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaggtarea2ActionPerformed

    private void txtfechafinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechafinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechafinalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DentroApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DentroApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DentroApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DentroApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DentroApp().setVisible(true);
            }
        });
    }
    private void informacionTareas(int ID){
        Connection cn = cnx.conexion();
        String SQL = "SELECT * FROM tareas WHERE IDUsuario = %s".formatted(ID);
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Tarea");
        tabla.addColumn("fechaCreacion");
        tabla.addColumn("Fecha de finalizacion");
        tblista.setModel(tabla);
        String data[] = new String[3];
        Statement st;
        try{
            st = (Statement) cn.createStatement();
            ResultSet rs =st.executeQuery(SQL);
            while (rs.next()){
                data[0] = rs.getString(2);
                data[1] = rs.getString(3);
                data[2] = rs.getString(4);
                tabla.addRow(data);
            }
            tblista.setModel(tabla);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Error en la consulta SQL: " + e);
        }
        cnx.cerrar();
      
        
    }
    private void limpiarCampos(){
        txtaggtarea2.setText("");
        txtfechainicio.setText("");
        txtfechafinal.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel act;
    private javax.swing.JLabel agg;
    private javax.swing.JLabel borr;
    private javax.swing.JButton btnact;
    private javax.swing.JButton btnagg;
    private javax.swing.JButton btnborr;
    private javax.swing.JButton btncomp;
    private javax.swing.JLabel comp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblista;
    private javax.swing.JTextField txtaggtarea2;
    private javax.swing.JTextField txtfechafinal;
    private javax.swing.JTextField txtfechainicio;
    // End of variables declaration//GEN-END:variables
}
